### ISSUE TITLE
Error message: "After contraction, there is more than one remaining node."

### ISSUE THREAD

**Issue by AlaricCheng** [aspuru-guzik-group/qtorch#2]
I was running qtorch from within the docker container.  But it displayed an error message `After contraction, there is more than one remaining node.`. I don't know where I have made a mistake. Below is my `inp` file:
```
# Line graph decomposition method for contraction

>int threads 5

>string qasm /qtorch-test/test/test.qasm

>string measurement /qtorch-test/test/test_m_5.txt

>string contractmethod linegraph-qbb

>int quickbbseconds 20

>string outputpath /qtorch-test/test/test.out

```
My `qasm` file: (`t.gate` and `cz.gate` are copied from the qtorch repo.)
```
5

def1 T /qtorch-test/gates/t.gate

def2 CZ /qtorch-test/gates/cz.gate

H 0 

H 1 

H 2 

H 3 

H 4 

T 0 

H 1 

T 2 

H 3 

CZ 3 4 

H 0 

T 1 

CZ 2 3 

T 3 

H 4 

CZ 0 1 

T 1 

T 2 

CZ 3 4 

T 4 

T 0 

T 1 

CZ 2 3 

H 3 

CZ 3 4 

H 0 

T 1 

CZ 2 3 

H 3 

CZ 3 4 

T 0 

T 1 

H 2 

H 3 

CZ 3 4 

T 0 

T 1 

T 2 

H 3 

H 4 
```
And my measurement file:
`0 0 0 0 1 `
So is there anything wrong with my files? Thank you!

**Comment by schuylerfried** [comment]
It seems like you never connect qubits 1 and 2 with a two qubit gate! Try adding `CZ 1 2` somewhere in the QASM file.

**Comment by AlaricCheng** [comment]
Thank you. Yes, it works if I add `CZ 1 2`...But that's strange, because if there are multiple disconnected nodes left after contraction, then their values should multiply to get a final probability. After all, there's no reason why a quantum circuit has to include two qubit gates. So can this be improved?

**Comment by schuylerfried** [comment]
Mathematically, you are correct, but why would you want to run a circuit with a disconnected qubit...?

**Comment by AlaricCheng** [comment]
Because sometimes we may want to do tests on circuits that are "slightly entangled". For example, if we want to compare different simulation methods, and some methods might work well when there are less entangling gates on a circuit, then it's natural to compare such method with qtorch and other existing simulators. Also, I suppose qtorch is a universal simulator, so it would be better if you can take as many scenarios as possible into account.

**Comment by schuylerfried** [comment]
@quantum-cheng, if you'd like to add this feature (it wouldn't be that hard), you can submit a PR for me to review. Otherwise, it might be a while before I can add this feature. I can tell you that from a complexity theoretic standpoint, what happens when you have a slightly entangled circuit is very well defined. Your time complexity increases as O(e^(treewidth_circuit_part_one)) + O(e^(treewidth_circuit_part_two))...., when you split the circuit into two or more fully entangled parts. Therefore, if you don't want to wait until I add this feature or submit a PR, just split the circuit into fully entangled parts and take the linear combination of all the simulation times.

**Comment by schuylerfried** [comment]
Also, the docker version is out of date with some small changes. Clone this repo for the bleeding edge version (that won't run your circuit at all unless it's fully entangled, instead of running part of it)

**Comment by schuylerfried** [comment]
Hey, https://github.com/aspuru-guzik-group/qtorch/pull/4 should fix this!
